# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true
  timeout: 5m

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - copyloopvar
    - depguard
    - execinquery
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gci
    - gochecknoglobals
    - gomnd
    - intrange
    - ireturn
    - lll
    - mnd
    - nolintlint # https://github.com/golangci/golangci-lint/issues/3063
    - nonamedreturns
    - paralleltest
    - tagliatelle
    - testifylint
    - testpackage
    - varnamelen
    - wrapcheck

issues:
  max-issues-per-linter: 200
  max-same-issues: 50
  exclude-use-default: false
  exclude-rules:
    - linters:
        - containedctx
        - dupl
        - err113
        - funlen
        - goconst
        - goerr113
        - gomnd
        - noctx
      path: "_test.go"
