dir: '{{.InterfaceDir}}/mock'
structname: '{{.InterfaceName}}'
filename: "{{ .InterfaceName | snakecase }}.go"
pkgname: mock
template: "https://raw.githubusercontent.com/nhatthm/mockery-template/0.3.0/templates/testify-mocker.templ"
template-data:
  unroll-variadic: true
packages:
  go.nhat.io/grpcmock/planner:
    config:
      dir: mock/planner
      include-interface-regex: ^(Expectation|Planner)$
      pkgname: planner
  google.golang.org/grpc:
    config:
      dir: mock/grpc
      include-interface-regex: ^(ClientStream|ServerStream)$
      pkgname: grpc
