dir: '{{.InterfaceDir}}/mock'
structname: '{{.InterfaceName}}'
filename: "{{ .InterfaceName | snakecase }}.go"
pkgname: mock
template: testify
template-data:
  unroll-variadic: true
packages:
  go.nhat.io/grpcmock/planner:
    config:
      dir: mock/planner
      include-interface-regex: ^(Expectation|Planner)$
      pkgname: planner
  google.golang.org/grpc:
    config:
      dir: mock/grpc
      include-interface-regex: ^(ClientStream|ServerStream)$
      pkgname: grpc
