// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: resources/protobuf/service.proto

package grpctest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_resources_protobuf_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resources_protobuf_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_resources_protobuf_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetItemRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_resources_protobuf_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resources_protobuf_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_resources_protobuf_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListItemsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CreateItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumItems      int64                  `protobuf:"varint,1,opt,name=num_items,json=numItems,proto3" json:"num_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemsResponse) Reset() {
	*x = CreateItemsResponse{}
	mi := &file_resources_protobuf_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemsResponse) ProtoMessage() {}

func (x *CreateItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resources_protobuf_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemsResponse.ProtoReflect.Descriptor instead.
func (*CreateItemsResponse) Descriptor() ([]byte, []int) {
	return file_resources_protobuf_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateItemsResponse) GetNumItems() int64 {
	if x != nil {
		return x.NumItems
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_resources_protobuf_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_resources_protobuf_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_resources_protobuf_service_proto_rawDescGZIP(), []int{3}
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

var File_resources_protobuf_service_proto protoreflect.FileDescriptor

const file_resources_protobuf_service_proto_rawDesc = "" +
	"\n" +
	" resources/protobuf/service.proto\x12\bgrpctest\x1a\x1fgoogle/protobuf/timestamp.proto\" \n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"/\n" +
	"\x10ListItemsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\"2\n" +
	"\x13CreateItemsResponse\x12\x1b\n" +
	"\tnum_items\x18\x01 \x01(\x03R\bnumItems\"\x7f\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12;\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime2\xf3\x01\n" +
	"\vItemService\x123\n" +
	"\aGetItem\x12\x18.grpctest.GetItemRequest\x1a\x0e.grpctest.Item\x129\n" +
	"\tListItems\x12\x1a.grpctest.ListItemsRequest\x1a\x0e.grpctest.Item0\x01\x12>\n" +
	"\vCreateItems\x12\x0e.grpctest.Item\x1a\x1d.grpctest.CreateItemsResponse(\x01\x124\n" +
	"\x0eTransformItems\x12\x0e.grpctest.Item\x1a\x0e.grpctest.Item(\x010\x01B\x19Z\x17test/grpctest/;grpctestb\x06proto3"

var (
	file_resources_protobuf_service_proto_rawDescOnce sync.Once
	file_resources_protobuf_service_proto_rawDescData []byte
)

func file_resources_protobuf_service_proto_rawDescGZIP() []byte {
	file_resources_protobuf_service_proto_rawDescOnce.Do(func() {
		file_resources_protobuf_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resources_protobuf_service_proto_rawDesc), len(file_resources_protobuf_service_proto_rawDesc)))
	})
	return file_resources_protobuf_service_proto_rawDescData
}

var file_resources_protobuf_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_resources_protobuf_service_proto_goTypes = []any{
	(*GetItemRequest)(nil),        // 0: grpctest.GetItemRequest
	(*ListItemsRequest)(nil),      // 1: grpctest.ListItemsRequest
	(*CreateItemsResponse)(nil),   // 2: grpctest.CreateItemsResponse
	(*Item)(nil),                  // 3: grpctest.Item
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_resources_protobuf_service_proto_depIdxs = []int32{
	4, // 0: grpctest.Item.create_time:type_name -> google.protobuf.Timestamp
	0, // 1: grpctest.ItemService.GetItem:input_type -> grpctest.GetItemRequest
	1, // 2: grpctest.ItemService.ListItems:input_type -> grpctest.ListItemsRequest
	3, // 3: grpctest.ItemService.CreateItems:input_type -> grpctest.Item
	3, // 4: grpctest.ItemService.TransformItems:input_type -> grpctest.Item
	3, // 5: grpctest.ItemService.GetItem:output_type -> grpctest.Item
	3, // 6: grpctest.ItemService.ListItems:output_type -> grpctest.Item
	2, // 7: grpctest.ItemService.CreateItems:output_type -> grpctest.CreateItemsResponse
	3, // 8: grpctest.ItemService.TransformItems:output_type -> grpctest.Item
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_resources_protobuf_service_proto_init() }
func file_resources_protobuf_service_proto_init() {
	if File_resources_protobuf_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resources_protobuf_service_proto_rawDesc), len(file_resources_protobuf_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resources_protobuf_service_proto_goTypes,
		DependencyIndexes: file_resources_protobuf_service_proto_depIdxs,
		MessageInfos:      file_resources_protobuf_service_proto_msgTypes,
	}.Build()
	File_resources_protobuf_service_proto = out.File
	file_resources_protobuf_service_proto_goTypes = nil
	file_resources_protobuf_service_proto_depIdxs = nil
}
