name: lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: nhatthm/gh-actions/checkout@master
      - uses: nhatthm/gh-actions/find-go-version@master
      - uses: nhatthm/gh-actions/setup-go@master
        with:
          go-version: ${{ env.GO_LATEST_VERSION }}
      - uses: nhatthm/gh-actions/golangci-lint@master
