---
name: 'update-registry'

on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: nhatthm/gh-actions/checkout@master
      - uses: nhatthm/gh-actions/notify-go-registries@master
        with:
          token: ${{ secrets.REGISTRY_TOKEN }}
