---
name: 'update-registry'

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  MODULE_NAME: grpcmock

jobs:
  notify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry: [ go.nhat.io, go-staging.nhat.io ]
    steps:
      - name: notify ${{ matrix.registry }}
        uses: benc-uk/workflow-dispatch@v121
        with:
          workflow: build
          repo: nhatthm/${{ matrix.registry }}
          token: ${{ secrets.REGISTRY_TOKEN }}
          inputs: '{"modules": "${{ env.MODULE_NAME }}"}'
          ref: 'master'
