// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package planner

import (
	mock "github.com/stretchr/testify/mock"
	"go.nhat.io/grpcmock/matcher"
	"go.nhat.io/grpcmock/service"
)

// NewExpectation creates a new instance of Expectation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpectation(t interface {
	mock.TestingT
	Cleanup(func())
}) *Expectation {
	mock := &Expectation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Expectation is an autogenerated mock type for the Expectation type
type Expectation struct {
	mock.Mock
}

type Expectation_Expecter struct {
	mock *mock.Mock
}

func (_m *Expectation) EXPECT() *Expectation_Expecter {
	return &Expectation_Expecter{mock: &_m.Mock}
}

// Fulfilled provides a mock function for the type Expectation
func (_mock *Expectation) Fulfilled() {
	_mock.Called()
	return
}

// Expectation_Fulfilled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fulfilled'
type Expectation_Fulfilled_Call struct {
	*mock.Call
}

// Fulfilled is a helper method to define mock.On call
func (_e *Expectation_Expecter) Fulfilled() *Expectation_Fulfilled_Call {
	return &Expectation_Fulfilled_Call{Call: _e.mock.On("Fulfilled")}
}

func (_c *Expectation_Fulfilled_Call) Run(run func()) *Expectation_Fulfilled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_Fulfilled_Call) Return() *Expectation_Fulfilled_Call {
	_c.Call.Return()
	return _c
}

func (_c *Expectation_Fulfilled_Call) RunAndReturn(run func()) *Expectation_Fulfilled_Call {
	_c.Run(run)
	return _c
}

// FulfilledTimes provides a mock function for the type Expectation
func (_mock *Expectation) FulfilledTimes() uint {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FulfilledTimes")
	}

	var r0 uint
	if returnFunc, ok := ret.Get(0).(func() uint); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint)
	}
	return r0
}

// Expectation_FulfilledTimes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FulfilledTimes'
type Expectation_FulfilledTimes_Call struct {
	*mock.Call
}

// FulfilledTimes is a helper method to define mock.On call
func (_e *Expectation_Expecter) FulfilledTimes() *Expectation_FulfilledTimes_Call {
	return &Expectation_FulfilledTimes_Call{Call: _e.mock.On("FulfilledTimes")}
}

func (_c *Expectation_FulfilledTimes_Call) Run(run func()) *Expectation_FulfilledTimes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_FulfilledTimes_Call) Return(v uint) *Expectation_FulfilledTimes_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *Expectation_FulfilledTimes_Call) RunAndReturn(run func() uint) *Expectation_FulfilledTimes_Call {
	_c.Call.Return(run)
	return _c
}

// HeaderMatcher provides a mock function for the type Expectation
func (_mock *Expectation) HeaderMatcher() matcher.HeaderMatcher {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HeaderMatcher")
	}

	var r0 matcher.HeaderMatcher
	if returnFunc, ok := ret.Get(0).(func() matcher.HeaderMatcher); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(matcher.HeaderMatcher)
		}
	}
	return r0
}

// Expectation_HeaderMatcher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeaderMatcher'
type Expectation_HeaderMatcher_Call struct {
	*mock.Call
}

// HeaderMatcher is a helper method to define mock.On call
func (_e *Expectation_Expecter) HeaderMatcher() *Expectation_HeaderMatcher_Call {
	return &Expectation_HeaderMatcher_Call{Call: _e.mock.On("HeaderMatcher")}
}

func (_c *Expectation_HeaderMatcher_Call) Run(run func()) *Expectation_HeaderMatcher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_HeaderMatcher_Call) Return(headerMatcher matcher.HeaderMatcher) *Expectation_HeaderMatcher_Call {
	_c.Call.Return(headerMatcher)
	return _c
}

func (_c *Expectation_HeaderMatcher_Call) RunAndReturn(run func() matcher.HeaderMatcher) *Expectation_HeaderMatcher_Call {
	_c.Call.Return(run)
	return _c
}

// PayloadMatcher provides a mock function for the type Expectation
func (_mock *Expectation) PayloadMatcher() *matcher.PayloadMatcher {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PayloadMatcher")
	}

	var r0 *matcher.PayloadMatcher
	if returnFunc, ok := ret.Get(0).(func() *matcher.PayloadMatcher); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*matcher.PayloadMatcher)
		}
	}
	return r0
}

// Expectation_PayloadMatcher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayloadMatcher'
type Expectation_PayloadMatcher_Call struct {
	*mock.Call
}

// PayloadMatcher is a helper method to define mock.On call
func (_e *Expectation_Expecter) PayloadMatcher() *Expectation_PayloadMatcher_Call {
	return &Expectation_PayloadMatcher_Call{Call: _e.mock.On("PayloadMatcher")}
}

func (_c *Expectation_PayloadMatcher_Call) Run(run func()) *Expectation_PayloadMatcher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_PayloadMatcher_Call) Return(payloadMatcher *matcher.PayloadMatcher) *Expectation_PayloadMatcher_Call {
	_c.Call.Return(payloadMatcher)
	return _c
}

func (_c *Expectation_PayloadMatcher_Call) RunAndReturn(run func() *matcher.PayloadMatcher) *Expectation_PayloadMatcher_Call {
	_c.Call.Return(run)
	return _c
}

// RemainTimes provides a mock function for the type Expectation
func (_mock *Expectation) RemainTimes() uint {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemainTimes")
	}

	var r0 uint
	if returnFunc, ok := ret.Get(0).(func() uint); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint)
	}
	return r0
}

// Expectation_RemainTimes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemainTimes'
type Expectation_RemainTimes_Call struct {
	*mock.Call
}

// RemainTimes is a helper method to define mock.On call
func (_e *Expectation_Expecter) RemainTimes() *Expectation_RemainTimes_Call {
	return &Expectation_RemainTimes_Call{Call: _e.mock.On("RemainTimes")}
}

func (_c *Expectation_RemainTimes_Call) Run(run func()) *Expectation_RemainTimes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_RemainTimes_Call) Return(v uint) *Expectation_RemainTimes_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *Expectation_RemainTimes_Call) RunAndReturn(run func() uint) *Expectation_RemainTimes_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceMethod provides a mock function for the type Expectation
func (_mock *Expectation) ServiceMethod() service.Method {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServiceMethod")
	}

	var r0 service.Method
	if returnFunc, ok := ret.Get(0).(func() service.Method); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(service.Method)
	}
	return r0
}

// Expectation_ServiceMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceMethod'
type Expectation_ServiceMethod_Call struct {
	*mock.Call
}

// ServiceMethod is a helper method to define mock.On call
func (_e *Expectation_Expecter) ServiceMethod() *Expectation_ServiceMethod_Call {
	return &Expectation_ServiceMethod_Call{Call: _e.mock.On("ServiceMethod")}
}

func (_c *Expectation_ServiceMethod_Call) Run(run func()) *Expectation_ServiceMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_ServiceMethod_Call) Return(method service.Method) *Expectation_ServiceMethod_Call {
	_c.Call.Return(method)
	return _c
}

func (_c *Expectation_ServiceMethod_Call) RunAndReturn(run func() service.Method) *Expectation_ServiceMethod_Call {
	_c.Call.Return(run)
	return _c
}
