// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package planner

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.nhat.io/grpcmock/planner"
	"go.nhat.io/grpcmock/service"
)

// NewPlanner creates a new instance of Planner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Planner {
	mock := &Planner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Planner is an autogenerated mock type for the Planner type
type Planner struct {
	mock.Mock
}

type Planner_Expecter struct {
	mock *mock.Mock
}

func (_m *Planner) EXPECT() *Planner_Expecter {
	return &Planner_Expecter{mock: &_m.Mock}
}

// Expect provides a mock function for the type Planner
func (_mock *Planner) Expect(expect planner.Expectation) {
	_mock.Called(expect)
	return
}

// Planner_Expect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Expect'
type Planner_Expect_Call struct {
	*mock.Call
}

// Expect is a helper method to define mock.On call
//   - expect planner.Expectation
func (_e *Planner_Expecter) Expect(expect any) *Planner_Expect_Call {
	return &Planner_Expect_Call{Call: _e.mock.On("Expect", expect)}
}

func (_c *Planner_Expect_Call) Run(run func(expect planner.Expectation)) *Planner_Expect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 planner.Expectation
		if args[0] != nil {
			arg0 = args[0].(planner.Expectation)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Planner_Expect_Call) Return() *Planner_Expect_Call {
	_c.Call.Return()
	return _c
}

func (_c *Planner_Expect_Call) RunAndReturn(run func(expect planner.Expectation)) *Planner_Expect_Call {
	_c.Run(run)
	return _c
}

// IsEmpty provides a mock function for the type Planner
func (_mock *Planner) IsEmpty() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEmpty")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Planner_IsEmpty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEmpty'
type Planner_IsEmpty_Call struct {
	*mock.Call
}

// IsEmpty is a helper method to define mock.On call
func (_e *Planner_Expecter) IsEmpty() *Planner_IsEmpty_Call {
	return &Planner_IsEmpty_Call{Call: _e.mock.On("IsEmpty")}
}

func (_c *Planner_IsEmpty_Call) Run(run func()) *Planner_IsEmpty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Planner_IsEmpty_Call) Return(b bool) *Planner_IsEmpty_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Planner_IsEmpty_Call) RunAndReturn(run func() bool) *Planner_IsEmpty_Call {
	_c.Call.Return(run)
	return _c
}

// Plan provides a mock function for the type Planner
func (_mock *Planner) Plan(ctx context.Context, req service.Method, in any) (planner.Expectation, error) {
	ret := _mock.Called(ctx, req, in)

	if len(ret) == 0 {
		panic("no return value specified for Plan")
	}

	var r0 planner.Expectation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, service.Method, any) (planner.Expectation, error)); ok {
		return returnFunc(ctx, req, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, service.Method, any) planner.Expectation); ok {
		r0 = returnFunc(ctx, req, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(planner.Expectation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, service.Method, any) error); ok {
		r1 = returnFunc(ctx, req, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Planner_Plan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Plan'
type Planner_Plan_Call struct {
	*mock.Call
}

// Plan is a helper method to define mock.On call
//   - ctx context.Context
//   - req service.Method
//   - in any
func (_e *Planner_Expecter) Plan(ctx any, req any, in any) *Planner_Plan_Call {
	return &Planner_Plan_Call{Call: _e.mock.On("Plan", ctx, req, in)}
}

func (_c *Planner_Plan_Call) Run(run func(ctx context.Context, req service.Method, in any)) *Planner_Plan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 service.Method
		if args[1] != nil {
			arg1 = args[1].(service.Method)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Planner_Plan_Call) Return(expectation planner.Expectation, err error) *Planner_Plan_Call {
	_c.Call.Return(expectation, err)
	return _c
}

func (_c *Planner_Plan_Call) RunAndReturn(run func(ctx context.Context, req service.Method, in any) (planner.Expectation, error)) *Planner_Plan_Call {
	_c.Call.Return(run)
	return _c
}

// Remain provides a mock function for the type Planner
func (_mock *Planner) Remain() []planner.Expectation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Remain")
	}

	var r0 []planner.Expectation
	if returnFunc, ok := ret.Get(0).(func() []planner.Expectation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]planner.Expectation)
		}
	}
	return r0
}

// Planner_Remain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remain'
type Planner_Remain_Call struct {
	*mock.Call
}

// Remain is a helper method to define mock.On call
func (_e *Planner_Expecter) Remain() *Planner_Remain_Call {
	return &Planner_Remain_Call{Call: _e.mock.On("Remain")}
}

func (_c *Planner_Remain_Call) Run(run func()) *Planner_Remain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Planner_Remain_Call) Return(expectations []planner.Expectation) *Planner_Remain_Call {
	_c.Call.Return(expectations)
	return _c
}

func (_c *Planner_Remain_Call) RunAndReturn(run func() []planner.Expectation) *Planner_Remain_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type Planner
func (_mock *Planner) Reset() {
	_mock.Called()
	return
}

// Planner_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type Planner_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *Planner_Expecter) Reset() *Planner_Reset_Call {
	return &Planner_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *Planner_Reset_Call) Run(run func()) *Planner_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Planner_Reset_Call) Return() *Planner_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *Planner_Reset_Call) RunAndReturn(run func()) *Planner_Reset_Call {
	_c.Run(run)
	return _c
}
