// Code generated by mockery v2.14.0. DO NOT EDIT.

package planner

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	planner "go.nhat.io/grpcmock/planner"

	service "go.nhat.io/grpcmock/service"
)

// Planner is an autogenerated mock type for the Planner type
type Planner struct {
	mock.Mock
}

// Expect provides a mock function with given fields: expect
func (_m *Planner) Expect(expect planner.Expectation) {
	_m.Called(expect)
}

// IsEmpty provides a mock function with given fields:
func (_m *Planner) IsEmpty() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Plan provides a mock function with given fields: ctx, req, in
func (_m *Planner) Plan(ctx context.Context, req service.Method, in interface{}) (planner.Expectation, error) {
	ret := _m.Called(ctx, req, in)

	var r0 planner.Expectation
	if rf, ok := ret.Get(0).(func(context.Context, service.Method, interface{}) planner.Expectation); ok {
		r0 = rf(ctx, req, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(planner.Expectation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, service.Method, interface{}) error); ok {
		r1 = rf(ctx, req, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remain provides a mock function with given fields:
func (_m *Planner) Remain() []planner.Expectation {
	ret := _m.Called()

	var r0 []planner.Expectation
	if rf, ok := ret.Get(0).(func() []planner.Expectation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]planner.Expectation)
		}
	}

	return r0
}

// Reset provides a mock function with given fields:
func (_m *Planner) Reset() {
	_m.Called()
}

type mockConstructorTestingTNewPlanner interface {
	mock.TestingT
	Cleanup(func())
}

// NewPlanner creates a new instance of Planner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPlanner(t mockConstructorTestingTNewPlanner) *Planner {
	mock := &Planner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
